# -*- coding: utf-8 -*-
"""Numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nSE-k8bc1MbtFdHFAUaGCdtsL8Ie8QSW
"""

import numpy as np

#Int Array
int_Array=np.array([1,2,3,4,5], dtype=int)
int_Array

#2D Array
org_arrya=np.array([[1,2,3],[4,5,6]])
org_arrya

#3D Array
Array_3D=np.array([[[1,2],[4,5]],[[7,8],[10,11]]])
Array_3D

#Array of 10 Equally spaced values
equal_Array= np.linspace(0,1,10)
equal_Array

#5 values paced array
array=np.logspace(0,2,5)
array

arra=np.arange(0,10,2)
arra

#3*3 with zeros
aray=np.zeros((3,3))
aray

#2*4 array with ones
array=np.ones((2,4))
array

#new array filled with ones & matching old arrays
ones_array=np.ones_like(array)
ones_array

array=np.array([2,8,9,7])
print(f"Dimesion:{array.ndim},Shape:{array.shape},Size:{array.size}")

array=np.array([2,8,9,77, 99, 66])
first_Elemet= array[0]
last_Element= array[-1]
print(f"First Element:{first_Elemet},Last Element:{last_Element}")

#2D Numpy array
arr_2d=np.array([[1,2,3],[5,6,7],[8,9,7]])

#slicing rows & column
sliced_array=arr_2d[0,1] #row 0 & column 1
print(sliced_array)

sl=arr_2d[1:4] #slice from index 1 to 3
print(sl)

sll=arr_2d[0::2] #start at index 0 & step by 2
print(sll)

slr=arr_2d[-2::] #acess last 2 elemnts
print(slr)

arr_2d=np.array([[1,2,3],[5,6,7],[8,9,7]])

sliced=arr_2d[1:3,0:2] #slice sub array 5-6, 8-9
print(sliced)

#Apped Array
org_array = np.array([8,9,8])
org_array=np.append(org_array, [5, 88, 5, 88])
print(org_array)

#Remove item at index 2
org_array = np.array([8,9,8])
arr=np.delete(org_array, 2)
print(arr)

org_array = np.array([[8,9,8], [4 , 8, 9], [5, 6, 7]])

#Remove Second row at Index 1
arr=np.delete(org_array, 1, axis=0)
print(arr)













































