# -*- coding: utf-8 -*-
"""Pandas Practice On US Airline Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VB5aXRaPaAu80aARB47Ye19-cRNkbub0
"""

import pandas as pd
from google.colab import files
uploaded=files.upload()

data = pd.read_csv("US Airline Flight Routes and Fares.csv")

data.head(5)

data.tail(5)

data.sample(5)

data.shape

data.info()

data.describe()

data.describe(include='object')

data.value_counts().head(5)

data.describe(include='all')

data.columns

data.fare_low.mean()

data.fare_low.mode()

data.isna().sum()

data.dropna()

data.isna().sum()

data.dropna(subset=['Geocoded_City1'],inplace=True)

data.head(3)

data.duplicated().sum()

data.city1.str.upper()

data.city2.str.upper()

def normal():
  minv = data.fare_low.min()
  maxv = data.fare_low.max()
  data.fare_low = (data.fare_low-minv)/(maxv-minv)
  return data.fare_low

def normal(value):
  minv = data.fare_low.min()
  maxv = data.fare_low.max()
  return (value - minv)/(maxv-minv)

data.fare_low = data.fare_low.apply(normal)

data.head(3)

