# -*- coding: utf-8 -*-
"""Simple RNN Implementation Using Keras.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cwOoMl8KiiL22vsyhcXmsiS5cO7CdaMg
"""

import numpy as np
import keras
from keras.models import Sequential
from keras.layers import SimpleRNN, Dense

np.random.seed(42)

X=np.random.rand(100,10,1)
y=np.random.randint(2, size=100)

model=Sequential()

model.add(SimpleRNN(32, input_shape=(10,1)))

model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.fit(X, Y, epochs=10, batch_size=32)





